#!/bin/bash
docker build \
  --build-arg VCS_REF=`git rev-parse HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=`git describe --tags --exact-match || git rev-parse HEAD` \
  -t $IMAGE_NAME .
